# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bindex` gem.
# Please instead update this file by running `bin/tapioca gem bindex`.

module ActiveSupport::Dependencies::Blamable
  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#339
  def blame_file!(file); end

  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#343
  def blamed_files; end

  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#352
  def copy_blame!(exc); end

  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#347
  def describe_blame; end
end

class Exception
  include ::ActiveSupport::Dependencies::Blamable
end
