# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `byebug` gem.
# Please instead update this file by running `bin/tapioca gem byebug`.

module ActiveSupport::Dependencies::Blamable
  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#339
  def blame_file!(file); end

  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#343
  def blamed_files; end

  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#352
  def copy_blame!(exc); end

  # source://activesupport/6.1.7/lib/active_support/dependencies.rb#347
  def describe_blame; end
end

# Reopen main module to define the library version
module Byebug
  class << self
    # Starts byebug, and stops at the first line of user's code.
    #
    # source://byebug//lib/byebug/attacher.rb#10
    def attach; end

    # source://byebug//lib/byebug/attacher.rb#21
    def spawn(host = T.unsafe(nil), port = T.unsafe(nil)); end
  end
end

# Extends the extension class to be able to pass information about the
# debugging environment from the c-extension to the user.
class Exception
  include ::ActiveSupport::Dependencies::Blamable
end
